[package]
name = "cate-server"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl-sys = "0.9.103"
reqwest = { version = "0.12.7" }
#tokio = { verson = "1", features = ["fill"] }
#jars = "0.1.1"
serde = "1.0.210"
