[package]
name = "cate-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[dependencies]
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"
