import { Button, VerticalBox, HorizontalBox, ProgressIndicator } from "std-widgets.slint";
import "./../OxygenMono-Regular.ttf";

export component AppWindow inherits Window {
//    callback request-increase-value();
    callback request-send-file();
    callback do-what-with-what();

    default-font-family: "Oxygen Mono";
    default-font-size: 20px;
    background: #73ffde;
    title: "Cate";

    min-height: 360px;
    min-width: 640px;

    max-height: 720px;
    max-width: 1280px;
    
    preferred-height: 100%;
    preferred-width: 100%;

    VerticalBox {
        height: 100%;
        HorizontalLayout {
//            Button {
//                text: "test button";
//                clicked => {
//
//                }
//            }
            Text {
                text: "cate";
                font-size: 50px;
            }
            alignment: center;
        }
//        HorizontalBox {
//        height: 50%;
//        width: 100%;

            Button {
                text: "send file out";
//                width: 200px;
//                height: 50px;
                padding: 10px;
                clicked => {
                    root.request-send-file();
                    self.text = "files sent out";
                }
            }
//        }
//        HorizontalBox {
//        alignment: center;
//            ProgressIndicator {
//                width: 200px;
//                height: 50px;
////                progress: 50%;
//            }
//        }
    }
}
