import { Button, VerticalBox } from "std-widgets.slint";
import "./../OxygenMono-Regular.ttf";

export component AppWindow inherits Window {
//    in-out property <int> counter: 42;
    callback request-increase-value();
    callback request-send-file();

    default-font-family: "Oxygen Mono";
    default-font-size: 20px;
    background: #73ffde;
    title: "Cate";

//    height: 360px;
//    width: 640px;

    min-height: 360px;
    min-width: 640px;

    max-height: 720px;
    max-width: 1280px;
    
    preferred-height: 100%;
    preferred-width: 100%;
    VerticalBox {
        HorizontalLayout {
            Text {
                text: "cate";
                font-size: 50px;
            }
            alignment: center;
        }
        HorizontalLayout {

            Button {
                text: "send file out";
                clicked => {
//                    root.request-send-file();
                    root.request-increase-value();
                    self.text = "files sent out";
                }
            }
//            Text {
//                font-size: 35px;
//            }
        }
    }
}
